language: node_js

install:
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  # build docs
  - gulp docs
  # disable gitub jekyll
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

  local_dir: docs
