language: node_js

install:
  - npm install
  - npm install -g npx

script:
  # build docs
  - npm run docs
  # disable gitub jekyll
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

  local_dir: docs
